# Generated by Django 3.0.2 on 2020-06-06 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BloodStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CharityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=12)),
                ('phone2', models.CharField(max_length=12)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='homePageGallary/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imageGallary/%Y/%m/%d/')),
                ('grid', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='majorObjectives/%Y/%m/%d/')),
                ('title', models.CharField(max_length=300)),
                ('smallDesc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ourlateststory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='homePageOurLatestStory/%Y/%m/%d/')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TempInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeNo', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchTitle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='homePageUpcomingEvents/%Y/%m/%d/')),
                ('title', models.CharField(max_length=300)),
                ('smallDesc', models.CharField(max_length=300)),
                ('goal', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=300)),
                ('question_date', models.DateTimeField(default=datetime.datetime.now)),
                ('answer', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nonprofitcharities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='homePageNonProfitCharitiesPic/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100)),
                ('smallDesc', models.CharField(max_length=1000)),
                ('CharityType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CharityType')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='information/%Y/%m/%d/')),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.CharField(max_length=9000)),
                ('CharityType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CharityType')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('donation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('donationType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DonationType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableBloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_donor_id', models.IntegerField(blank=True, null=True)),
                ('blood_donor_name', models.CharField(blank=True, max_length=100)),
                ('doonation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('expire_date', models.DateTimeField(default=datetime.datetime.now)),
                ('receiver_id', models.CharField(blank=True, max_length=100)),
                ('receiver_name', models.CharField(blank=True, max_length=100)),
                ('apply_date', models.DateTimeField(blank=True)),
                ('blood_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BloodGroup')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BloodStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Auth_user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('is_user', models.BooleanField(default=True)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('educational_bg', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, default='profilePictures/user.png', max_length=255, upload_to='profilePictures/%Y/%m/%d/')),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BloodGroup')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
