# Generated by Django 3.1.2 on 2020-10-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200607_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(max_length=20)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_blood_group', models.CharField(max_length=20)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('donor_contact', models.CharField(max_length=11)),
                ('donor_city', models.CharField(max_length=100)),
            ],
        ),
    ]
